# Generated by Django 3.2.7 on 2021-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
