# Generated by Django 3.2.7 on 2021-10-06 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='firstname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='نام را فارسی یا انگلیسی استفاده نمایید', regex='^\\D+$')], verbose_name='نام پاسخگو'),
        ),
        migrations.AlterField(
            model_name='responder',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن را کامل وارد نمایید-برای ثابت کد استان نیاز میباشد', regex='^0[0-9]{10}$')], verbose_name='تلفن تماس پاسخگو'),
        ),
    ]
