# Generated by Django 3.2.7 on 2021-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='مقدار'),
        ),
    ]
