# Generated by Django 3.2.7 on 2021-09-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0002_alter_option_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_other_in_options',
            field=models.BooleanField(default=False, verbose_name='سایر دارد؟'),
        ),
    ]
