# Generated by Django 3.2.7 on 2021-09-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0003_question_has_other_in_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان دسته بندی')),
                ('value', models.PositiveSmallIntegerField(verbose_name='کد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agah.brandcategory', verbose_name='دسته بندی')),
            ],
        ),
    ]
