# Generated by Django 3.2.7 on 2021-09-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0004_brand_brandcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['category', 'value'], 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'ordering': ['pk'], 'verbose_name': 'محصولات-دسته بندی', 'verbose_name_plural': 'محصولات-دسته بندی'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='Agah.brandcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان دسته بندی'),
        ),
    ]
