# Generated by Django 3.2.7 on 2021-09-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0005_auto_20210919_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
