# Generated by Django 3.2.7 on 2021-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0006_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='کد'),
        ),
    ]
