# Generated by Django 3.2.7 on 2021-09-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0007_alter_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
        migrations.RemoveField(
            model_name='region',
            name='question',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
