# Generated by Django 3.2.7 on 2021-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0008_auto_20210919_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='day',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='شماره پرسشنامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='max_input_value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='min_input_value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responder',
            name='address',
            field=models.TextField(default=None, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='date',
            field=models.DateField(verbose_name='تاریخ شمسی'),
        ),
    ]
