# Generated by Django 3.2.7 on 2021-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0009_auto_20210919_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='پاسخ دادن اجباری است؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_input_value',
            field=models.PositiveIntegerField(verbose_name='حداکثر(فقط در فیلدهای عددی کاربری دارد)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_input_value',
            field=models.PositiveIntegerField(verbose_name='حداقل(فقط در فیلدهای عددی کاربری دارد)'),
        ),
    ]
