# Generated by Django 3.2.7 on 2021-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0010_auto_20210919_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_nothing_in_options',
            field=models.BooleanField(default=False, verbose_name='هیچکدام دارد؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='اجباری است؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_input_value',
            field=models.PositiveIntegerField(verbose_name='حداکثر(فیلدهای عددی)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_input_value',
            field=models.PositiveIntegerField(verbose_name='حداقل(فیلدهای عددی)'),
        ),
    ]
