# Generated by Django 3.2.7 on 2021-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0011_auto_20210919_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری است؟'),
        ),
    ]
