# Generated by Django 3.2.7 on 2021-09-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0012_alter_question_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='lastname',
        ),
    ]
