# Generated by Django 3.2.7 on 2021-09-20 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0013_remove_responder_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='number',
            field=models.PositiveIntegerField(verbose_name='شماره پرسشنامه'),
        ),
        migrations.AlterField(
            model_name='responder',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل را به صورت کامل وارد نمایید', regex='^09[0-9]{9}$')], verbose_name='تلفن تماس پاسخگو'),
        ),
    ]
