# Generated by Django 3.2.7 on 2021-09-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0014_auto_20210920_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='child',
            name='responder',
        ),
        migrations.DeleteModel(
            name='Limit',
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question', 'pk'], 'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه'},
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
