# Generated by Django 3.2.7 on 2021-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0015_auto_20210922_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['category', 'title'], 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'ordering': ['title'], 'verbose_name': 'محصولات-دسته بندی', 'verbose_name_plural': 'محصولات-دسته بندی'},
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='social_class',
            field=models.CharField(editable=False, max_length=1, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_input_value',
            field=models.PositiveIntegerField(verbose_name='حداکثر(عددی-متن)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_input_value',
            field=models.PositiveIntegerField(verbose_name='حداقل(عدد-متن)'),
        ),
    ]
