# Generated by Django 3.2.7 on 2021-09-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0016_auto_20210922_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['pk'], 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'verbose_name': 'محصولات-دسته بندی', 'verbose_name_plural': 'محصولات-دسته بندی'},
        ),
        migrations.AddField(
            model_name='brand',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Agah.question', verbose_name='پرسش'),
        ),
    ]
