# Generated by Django 3.2.7 on 2021-10-08 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender')),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married')], null=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Occupation')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About me')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('point', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='How much you know about it')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('point', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='How much you know about it')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('start_dte', models.DateField(blank=True, null=True, verbose_name='From')),
                ('end_dte', models.DateField(blank=True, null=True, verbose_name='To')),
                ('already_work', models.BooleanField(blank=True, default=False, null=True, verbose_name='I already work')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('university', models.CharField(blank=True, max_length=200, null=True, verbose_name='University')),
                ('from_dte', models.DateField(blank=True, null=True, verbose_name='From')),
                ('to_dte', models.DateField(blank=True, null=True, verbose_name='To')),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='Average')),
                ('degree', models.IntegerField(blank=True, choices=[(1, 'Diploma'), (2, 'Associate'), (3, 'Bachelor'), (4, 'Master'), (5, 'Doctoral'), (6, 'Post-Doc')], null=True, verbose_name='Degree')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('have_cert', models.BooleanField(blank=True, default=False, null=True, verbose_name='Do you have certificate?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('authorized_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Authorized by')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Certificate Url')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Portfolio.profile')),
            ],
        ),
    ]
