# Generated by Django 3.2.7 on 2021-10-08 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langauge', models.CharField(default='English', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='language',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates',
                                    to='Portfolio.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations',
                                    to='Portfolio.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs',
                                    to='Portfolio.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages',
                                    to='Portfolio.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills',
                                    to='Portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
