# Generated by Django 3.2.7 on 2021-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20211008_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='langauge',
            new_name='language',
        ),
    ]
