# Generated by Django 3.2.7 on 2021-10-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_alter_skill_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='point',
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1-Beginner', 'A1'), ('A2-Elementary', 'A2'), ('B1-Intermediate', 'B1'), ('B2-Upper Intermediate', 'B2'), ('C1-Advanced', 'C1'), ('C2-Proficiency', 'C2')], default='exit', max_length=21),
            preserve_default=False,
        ),
    ]
